name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2
    - uses: actions/checkout@master
    - name: Build
      run: |
        npm ci
        npm run build
    - name: WordPress Plugin Deploy
      uses: nk-o/action-wordpress-plugin-deploy@master
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SOURCE_DIR: gui-for-lcp/
